export declare const merchantCreateSchema: any;
export declare const merchantUpdateSchema: any;
export declare function merchantChangePasswordSchema(isAdmin: boolean): any;
export declare const merchantForgotPasswordSchema: any;
export declare const merchantResetPasswordSchema: any;
export declare const merchantCreateVerificationSchema: any;
export declare const merchantUpdateVerificationSchema: any;
export declare const merchantCreateVerifySchema: any;
export declare const merchantTransactionHistory: any;
export declare const merchantBanSchema: any;
