"use strict";
exports.UNKNOWN = "UNKNOWN_ERROR";
exports.NOT_AUTHORIZED = "NOT_AUTHORIZED";
exports.FORBIDDEN = "FORBIDDEN_ACCESS";
exports.CONFLICTED = "CONFLICTED_RESOURCE";
exports.NOT_FOUND = "NOT_FOUND";
exports.INTERNAL_ERROR = "INTERNAL_ERROR";
exports.BAD_REQUEST = "BAD_REQUEST";
exports.VALIDATION_ERROR = "VALIDATION_ERROR";
exports.SDK_WRONG_CREDENTIALS = "SDK_WRONG_CREDENTIALS";
//# sourceMappingURL=ErrorsConstants.js.map