"use strict";

exports.BAD_REQUEST = "BAD_REQUEST";
exports.NOT_AUTHORIZED = "NOT_AUTHORIZED";
exports.FORBIDDEN = "FORBIDDEN_ACCESS";
exports.NOT_FOUND = "NOT_FOUND";
exports.NOT_ALLOWED = "HTTP_METHOD_NOT_ALLOWED";
exports.CONFLICTED = "CONFLICTED_RESOURCE";
exports.TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
exports.INTERNAL_ERROR = "INTERNAL_ERROR";
exports.SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE";
exports.VALIDATION_ERROR = "VALIDATION_ERROR";
exports.UNKNOWN = "UNKNOWN_ERROR";
//# sourceMappingURL=ErrorsConstants.js.map