export declare const UNKNOWN: string;
export declare const NOT_AUTHORIZED: string;
export declare const FORBIDDEN: string;
export declare const CONFLICTED: string;
export declare const NOT_FOUND: string;
export declare const INTERNAL_ERROR: string;
export declare const BAD_REQUEST: string;
export declare const VALIDATION_ERROR: string;
export declare const SDK_WRONG_CREDENTIALS: string;
